import { ScoredRfp, BusinessProfile } from '@/types';
import { format } from 'date-fns';

interface EmailParams {
  clientName: string;
  rfp: ScoredRfp;
  businessProfile: BusinessProfile;
  brief?: string;
}

export function buildClientEmail({ clientName, rfp, businessProfile, brief }: EmailParams): string {
  return `Subject: Strategic RFP Opportunity - ${rfp.title}

Dear ${clientName},

I hope this message finds you well. I've identified a highly relevant RFP opportunity that aligns exceptionally well with your capabilities.

**RFP OVERVIEW**
• Title: ${rfp.title}
• Agency: ${rfp.sponsor}
• Due Date: ${format(new Date(rfp.dueDate), 'MMMM dd, yyyy')} (${Math.ceil((new Date(rfp.dueDate).getTime() - Date.now()) / (1000 * 60 * 60 * 24))} days)
• Award Range: ${rfp.amountText || 'See details'}
• Competition Level: ${getCompetitionLevel(rfp.score)}

**WHY THIS IS A STRONG FIT**
${rfp.matchReasons.map(reason => `• ${reason}`).join('\n')}

**YOUR COMPETITIVE ADVANTAGES**
${businessProfile.keyDifferentiators?.slice(0, 3).map(diff => `• ${diff}`).join('\n')}

${brief ? `**STRATEGIC INSIGHTS**\n${brief}\n` : ''}

**NEXT STEPS**
1. Review full RFP: ${rfp.url}
2. Confirm interest by ${format(new Date(Date.now() + 3 * 24 * 60 * 60 * 1000), 'MMM dd')}
3. Schedule proposal kickoff meeting
4. Assign proposal manager

**DEADLINE ALERT** ⏰
Based on typical proposal development cycles, I recommend starting immediately to ensure a competitive submission.

CONFIDENCE SCORE: ${rfp.score}% - ${getConfidenceInterpretation(rfp.score)}

Please let me know if you'd like me to:
- Prepare a detailed gap analysis
- Draft a capability matrix
- Schedule a strategy session
- Connect you with teaming partners

Best regards,
Your RFP Team

---
This email was generated by RFPMatch AI. Visit your dashboard for more opportunities.`;
}

export function buildInternalReviewEmail(rfp: ScoredRfp, businessProfile: BusinessProfile): string {
  return `**RFP REVIEW REQUIRED**

Score: ${rfp.score}/100 | Confidence: ${rfp.confidence}%

**Document Analysis:**
- Sector Match: ${businessProfile.sector === rfp.title.split(' ')[0] ? '✅' : '⚠️'}
- Location: ${rfp.location}
- Certifications Required: ${rfp.certifications?.join(', ') || 'None specified'}

**Recommendations:**
${rfp.score >= 80 ? '✅ PROCEED - High probability opportunity' : ''}
${rfp.score >= 60 && rfp.score < 80 ? '⚠️ EVALUATE - Moderate fit, consider teaming' : ''}
${rfp.score < 60 ? '❌ PASS - Low alignment with core capabilities' : ''}

**Action Items:**
- [ ] Verify NAICS code eligibility
- [ ] Check past performance requirements
- [ ] Assess resource availability
- [ ] Identify potential teaming partners`;
}

function getCompetitionLevel(score: number): string {
  if (score >= 80) return 'High probability';
  if (score >= 60) return 'Moderate probability';
  return 'Challenging';
}

function getConfidenceInterpretation(score: number): string {
  if (score >= 90) return 'Excellent match';
  if (score >= 70) return 'Strong match';
  if (score >= 50) return 'Moderate match';
  return 'Review recommended';
}
